# -*- coding: utf-8 -*-
"""DAP104

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifOmeelCJKPjujnh9Cn-_xzEwms9QIVB
"""

def hitung_norm_l1(vektor):
    """
    Rumus Norm L1 Jumlah dari nilai absolut setiap elemen vektor
    """
    total = 0
    for elemen in vektor:
        if elemen < 0:
            total += -elemen
        else:
            total += elemen
    return total


def hitung_norm_l2(vektor):
    """
    Rumus Norm L2 Akar kuadrat dari jumlah kuadrat setiap elemen vektor
    """
    total_kuadrat = 0
    for elemen in vektor:
        total_kuadrat += elemen ** 2

    norm_l2 = total_kuadrat ** 0.5
    return norm_l2


def dot_product_vektor(vektor_a, vektor_b):
    """
    Rumus Dot Product (a1*b1) + (a2*b2) + ... + (an*bn)
    """
    if len(vektor_a) != len(vektor_b):
        return None

    total = 0
    for i in range(len(vektor_a)):
        total += vektor_a[i] * vektor_b[i]
    return total


def cek_ortogonal(vektor_a, vektor_b):
    """
    Mengecek apakah dua vektor saling tegak lurus (Ortogonal).
    Syaratnya Hasil dot product harus mendekati atau sama dengan 0.
    """
    dot_product = dot_product_vektor(vektor_a, vektor_b)

    if dot_product is None:
        print("Panjang kedua vektor harus sama!")
        return False

    return abs(dot_product) < 1e-9


def cek_orthonormal(gabungan_vektor):
    """
    Mengecek apakah seluruh vektor bersifat Ortonormal.
    Syarat:
    1. Setiap vektor harus berupa Unit Vector (memiliki panjang/Norm L2 = 1).
    2. Setiap pasangan vektor yang berbeda harus saling tegak lurus (Ortogonal/Dot Product = 0).
    """
    n = len(gabungan_vektor)

    for i in range(n):
        panjang = hitung_norm_l2(gabungan_vektor[i])
        if abs(panjang - 1.0) > 1e-9:
            return False

    for i in range(n):
        for j in range(i + 1, n):
            if not cek_ortogonal(gabungan_vektor[i], gabungan_vektor[j]):
                return False
    return True

def hitung_frobenius_norm(matriks):
    """
    Menghitung Norma Frobenius dari matriks m x n.
    Rumusnya Akar kuadrat dari jumlah kuadrat seluruh elemen matriks.
    """
    total_kuadrat = 0
    for baris in matriks:
        for elemen in baris:
            total_kuadrat += elemen ** 2

    return total_kuadrat ** 0.5

def hadamard_product(matriks_a, matriks_b):
    if len(matriks_a) != len(matriks_b) or len(matriks_a[0]) != len(matriks_b[0]):
        return None

    jumlah_baris = len(matriks_a)
    jumlah_kolom = len(matriks_a[0])

    hasil = [[0 for _ in range(jumlah_kolom)] for _ in range(jumlah_baris)]

    for i in range(jumlah_baris):
        for j in range(jumlah_kolom):
            hasil[i][j] = matriks_a[i][j] * matriks_b[i][j]

    return hasil

def dot_product_matriks(matriks_a, matriks_b):
    if len(matriks_a[0]) != len(matriks_b):
        return None

    baris_a = len(matriks_a)
    kolom_a = len(matriks_a[0])
    kolom_b = len(matriks_b[0])

    hasil = [[0 for _ in range(kolom_b)] for _ in range(baris_a)]
    for i in range(baris_a):
        for j in range(kolom_b):
            total = 0
            for k in range(kolom_a):
                total += matriks_a[i][k] * matriks_b[k][j]
            hasil[i][j] = total

    return hasil

def transpos_matriks(matriks):
    jumlah_baris = len(matriks)
    jumlah_kolom = len(matriks[0])

    hasil = [[0 for _ in range(jumlah_baris)] for _ in range(jumlah_kolom)]
    for i in range(jumlah_baris):
        for j in range(jumlah_kolom):
            hasil[j][i] = matriks[i][j]
    return hasil


def matriks_simetris(matriks):
    matriks_transpos = transpos_matriks(matriks)
    if matriks == matriks_transpos:
        return True
    else:
        return False


def cek_matriks_identitas(matriks):
    """
    Memeriksa apakah matriks termasuk matriks identitas.
    Syaratnya Elemen diagonal utama bernilai 1, elemen lainnya bernilai 0.
    """
    jumlah_baris = len(matriks)
    jumlah_kolom = len(matriks[0])

    if jumlah_baris != jumlah_kolom:
        return False

    for i in range(jumlah_baris):
        for j in range(jumlah_kolom):
            if i == j:
                if abs(matriks[i][j] - 1.0) > 1e-9:
                    return False
            else:
                if abs(matriks[i][j]) > 1e-9:
                    return False
    return True


def invers_matriks_2x2(matriks):
    """
    Menghitung matriks invers khusus untuk ordo 2x2.
    Lengkap dengan validasi matriks singular (determinan = 0).
    """
    if len(matriks) != 2 or len(matriks[0]) != 2:
        print("Fungsi ini khusus untuk matriks 2x2.")
        return None

    a = matriks[0][0]
    b = matriks[0][1]
    c = matriks[1][0]
    d = matriks[1][1]

    determinan = (a * d) - (b * c)

    if abs(determinan) < 1e-9:
        print("Matriks singular (Determinannya 0), tidak memiliki invers!")
        return None

    faktor = 1 / determinan
    invers = [
        [d * faktor, -b * faktor],
        [-c * faktor, a * faktor]
    ]

    return invers


def hitung_determinan_3x3(m):
    """
    Menghitung determinan matriks 3x3 menggunakan Metode Sarrus.
    """
    a, b, c = m[0][0], m[0][1], m[0][2]
    d, e, f = m[1][0], m[1][1], m[1][2]
    g, h, i = m[2][0], m[2][1], m[2][2]

    det = (a*e*i + b*f*g + c*d*h) - (c*e*g + a*f*h + b*d*i)
    return det


def invers_matriks_3x3(matriks):
    """
    Menghitung invers matriks (A^-1) khusus untuk 3x3.
    """
    if len(matriks) != 3 or len(matriks[0]) != 3:
        print("Fungsi ini khusus untuk matriks 3x3.")
        return None

    det = hitung_determinan_3x3(matriks)
    if abs(det) < 1e-9:
        print("Matriks singular (Determinan = 0), tidak memiliki invers!")
        return None
    m = matriks
    kofaktor = [
        [
            (m[1][1]*m[2][2] - m[1][2]*m[2][1]),
            -(m[1][0]*m[2][2] - m[1][2]*m[2][0]),
            (m[1][0]*m[2][1] - m[1][1]*m[2][0])
        ],
        [
            -(m[0][1]*m[2][2] - m[0][2]*m[2][1]),
            (m[0][0]*m[2][2] - m[0][2]*m[2][0]),
            -(m[0][0]*m[2][1] - m[0][1]*m[2][0])
        ],
        [
            (m[0][1]*m[1][2] - m[0][2]*m[1][1]),
            -(m[0][0]*m[1][2] - m[0][2]*m[1][0]),
            (m[0][0]*m[1][1] - m[0][1]*m[1][0])
        ]
    ]

    adjoin = transpos_matriks(kofaktor)

    invers = [[adjoin[i][j] / det for j in range(3)] for i in range(3)]

    return invers